### PR TITLE
alternatives: replace master/slave with leader/follower

### LINKED ISSUE #80: /usr/sbin/alternatives needs to support more inclusive terminology
Per the IETF's [draft-knodel-terminology](https://datatracker.ietf.org/doc/draft-knodel-terminology/) memo and [Inclusive Naming Initiative](https://inclusivenaming.org/faqs/#what-terms-are-we-recommending-you-consider) (of which the Linux Foundation and Red Hat are both members of), please consider deprecating the use of "`master/slave`" terminology in this program and replacing them with a more inclusive pair like "`leader/follower`".

Given that there will be some use-cases or scripts out there that will rely on `alternatives` current behaviour and parameters for years to come, I'm under no illusion that compatibility/legacy shims will be around for years if not a decade or more to come.

### PR DESCRIPTION
**Pull request by lnykryn**
fixes #80

### CODE REVIEW

**Comment by netsnipe** [comment]
[lnykryn](https://github.com/lnykryn): I took a quick look at your patch and I can't see where support for `master/slave` is being retained to stay compatible with older packages/systems (especially those on the periphery of the Fedora/RHEL ecosystem). Might cutting over now without an transition period reinforced by `rpmlint` warnings to educate developers first cause breakages?

**Comment by lnykryn** [comment]
@netsnipe take a second look. This should be fully backwards compatible and I have even tweak the tests to check both the next and old scheme.

https://github.com/lnykryn/chkconfig/blob/leader/follower/alternatives.c#L1277
https://github.com/lnykryn/chkconfig/blob/leader/follower/test-alternatives.sh#L126

**Comment by jamacku** [comment]
@lnykryn Could you please rebase your PR on top of current `main`. Thanks

**Comment by lnykryn** [comment]
@jamacku done

**Pull request merged**
