### PR TITLE
Family mentioned for --set in both man and help

### PR DESCRIPTION
**Pull request by judovana**

### CODE REVIEW

**Comment by judovana** [comment]
Please don't be kind. As this is text-only change, I must admit that I have terrible style...

**Comment by judovana** [comment]
Also i see that there is [po/chkconfig.pot](https://github.com/fedora-sysv/chkconfig/pull/70/files#diff-210db48e269c1e3261372bfb9c01881425037bcbee37bd7375ccb0a072a39058) fiel in the commit. Is it desired? It is obviously autogenerated. And it seesm it got the last SeLinux change....

**Review by lnykryn — APPROVED** [review]

**Comment by judovana** [comment]
wait, what?-) I was half expecting "that would be to debian incompatible"

TY!

**Comment by lnykryn** [comment]
There was nothing wrong with the PR, the pot files are automatically generated translations and Debian has its own implementation :-)

**Pull request merged**
