### PR TITLE
[WIP] Separate alternatives from chkconfig

### PR DESCRIPTION
**Pull request by jamacku**
This pull request is trying to remove all alternatives related source code, files and etc.

Alternatives will be stored in separate repository as they should according to packaging guidelines.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@jamacku This doesn't make sense... Why is this necessary? Subpackaging it is sufficient enough...

**Comment by jamacku** [comment]
We are not expecting to separate alternatives and chkconfig right now. But in future they might be separated, because, they are two unrelated packages packaged as one and this is not right acourding to Fedora packaging guidelines.

**Comment by dustymabe** [comment]
This was separated in the fedora packaging: https://src.fedoraproject.org/rpms/chkconfig/c/bc410609930087abd41eb4ac2b741bf9d02ca317?branch=master

Maybe we could get it upstream?

**Comment by jamacku** [comment]
@dustymabe thanks for info. Upstream is now in sync with fedora.

I'm closing this one.

**Pull request closed without merging**
